font: 
  size: 15
  offset: 
    x: 0
    y: 8
  normal:
    family: JetBrainsMono Nerd Font Mono
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font Mono
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font Mono
    style: Italic

# Colors (Tomorrow Night)
colors:
 primary:
   background: '#1c1c1c'
   foreground: '#c5c8c6'
   dim_foreground: '#828482'
   bright_foreground: '#eaeaea'

 cursor:
   text: CellBackground
   cursor: CellForeground

 vi_mode_cursor:
   text: CellBackground
   cursor: CellForeground

 search:
  matches:
    foreground: '#000000'
    background: '#ffffff'
  focused_match:
    foreground: '#ffffff'
    background: '#000000'

  bar:
    background: '#c5c8c6'
    foreground: '#1c1c1c'

 hints:
  start:
    foreground: '#1c1c1c'
    background: '#e9ff5e'
  end:
    foreground: '#e9ff5e'
    background: '#1c1c1c'

 line_indicator:
   foreground: None
   background: None

 selection:
   text: CellBackground
   background: CellForeground

 normal:
   black:   '#1c1c1c'
   red:     '#cc6666'
   green:   '#b5bd68'
   yellow:  '#f0c674'
   blue:    '#81a2be'
   magenta: '#b294bb'
   cyan:    '#8abeb7'
   white:   '#c5c8c6'

 bright:
   black:   '#282a2e'
   red:     '#cc6666'
   green:   '#b5bd68'
   yellow:  '#f0c674'
   blue:    '#81a2be'
   magenta: '#b294bb'
   cyan:    '#8abeb7'
   white:   '#eaeaea'

 dim:
   black:   '#131415'
   red:     '#864343'
   green:   '#777c44'
   yellow:  '#9e824c'
   blue:    '#556a7d'
   magenta: '#75617b'
   cyan:    '#5b7d78'
   white:   '#828482'

 indexed_colors: []
